defaults: &defaults
  app_name: 'Barong'

  email:
    default_from: 'Barong <noreply@barong.io>'
    admin: 'admin@barong.io'

  url:
    host: 'localhost'
    scheme: 'http'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
