defaults: &defaults
  app_name: 'Barong'

  email:
    default_from: 'Barong <noreply@barong.io>'
    admin: 'admin@barong.io'

  url_host: 'localhost'
  url_scheme: 'http'
  
  rails_max_threads: 5
  port: 3000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
